# Generated by Django 4.0.8 on 2022-11-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCountry',
            fields=[
                ('id_Country', models.AutoField(db_column='id_Country', primary_key=True, serialize=False)),
                ('nameCountry', models.CharField(db_column='nameCountry', max_length=255)),
            ],
            options={
                'db_table': 'Tb_Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbDeviceType',
            fields=[
                ('id_DeviceType', models.AutoField(db_column='id_DeviceType', primary_key=True, serialize=False)),
                ('nameDeviceType', models.CharField(db_column='nameDeviceType', max_length=255)),
            ],
            options={
                'db_table': 'Tb_DeviceType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbHwPlatform',
            fields=[
                ('id_HwPlatform', models.AutoField(db_column='id_HwPlatform', primary_key=True, serialize=False)),
                ('nameHwPlatform', models.CharField(db_column='nameHwPlatform', max_length=255)),
            ],
            options={
                'db_table': 'TB_HwPlatform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbOs',
            fields=[
                ('id_Os', models.AutoField(db_column='Id_Os', primary_key=True, serialize=False)),
                ('nameOs', models.CharField(db_column='nameOs', max_length=255)),
            ],
            options={
                'db_table': 'TB_Os',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbSettingsType',
            fields=[
                ('id_SettingsType', models.AutoField(db_column='id_SettingsType', primary_key=True, serialize=False)),
                ('nameSettingsType', models.CharField(db_column='nameSettingsType', max_length=255)),
            ],
            options={
                'db_table': 'TB_settingsType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbTokenType',
            fields=[
                ('id_TokenType', models.AutoField(db_column='id_TokenType', primary_key=True, serialize=False)),
                ('nameToken', models.CharField(db_column='nameToken', max_length=255)),
            ],
            options={
                'db_table': 'TB_TokenType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbCity',
            fields=[
                ('id_City', models.AutoField(db_column='id_City', primary_key=True, serialize=False)),
                ('nameCity', models.CharField(db_column='nameCity', max_length=255)),
                ('id_Country', models.ForeignKey(db_column='id_Country', on_delete=django.db.models.deletion.PROTECT, to='crud.tbcountry')),
            ],
            options={
                'db_table': 'Tb_City',
                'managed': True,
            },
        ),
    ]
