# Generated by Django 4.0.8 on 2022-11-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbsettingstype',
            table='Tb_SettingsType',
        ),
    ]
